app/urls.py
from django.urls import path

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('cards/<str:set_id>/', views.card_list, name='card_list'),
    path('cards/<str:card_id>/images/', views.card_image, name='card_image'),
    path('search/', views.card_search, name='card_search'),
    path('toggle_mode/', views.toggle_view_mode, name='toggle_mode'),
    path('toggle_mode/<str:mode>/', views.toggle_view_mode, name='toggle_mode'),
]

mtg/urls.py
# from django.contrib import admin
from django.urls import path, include

from app.views import customhandler404

app_name = 'mtg'

urlpatterns = [
    path('', include('app.urls')),
]
handler404 = customhandler404

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

app/views.py
import json
import re

import requests
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from mtgsdk import Card
from mtgsdk import Set

from app.forms import SearchForm

SCRYFALL_API = 'https://api.scryfall.com/'
SCRYFALL_SETS = SCRYFALL_API + 'sets/'
SCRYFALL_SYMBOLS = SCRYFALL_API + 'symbology/'
SCRYFALL_URI = 'https://svgs.scryfall.io/card-symbols/'


def toggle_view_mode(request, mode: str = None):
    if mode is not None:
        if mode == 'dark':
            response = HttpResponse('<i id="toggle-mode" class="fa fa-sun-o text-light"></i>')
            response.set_cookie('toggle_mode', 'dark')
        else:
            response = HttpResponse('<i id="toggle-mode" class="fa fa-moon-o text-dark"></i>')
            response.set_cookie('toggle_mode', None)
    else:
        response = HttpResponse('<i id="toggle-mode" class="fa fa-moon-o text-dark"></i>')
        response.set_cookie('toggle_mode', None)
    return response


def customhandler404(request, exception, template_name='404.html'):
    response = render(request, template_name)
    response.status_code = 404
    return response


def get_sets() -> list[dict]:
    res = requests.get(SCRYFALL_SETS)
    data = res.json()
    # print(data)
    return data['data']


def get_symbol_uri(symbol: str) -> str:
    return f'https://svgs.scryfall.io/card-symbols/{str(symbol).strip("{}")}.svg'


def convert_symbols(text: str) -> str:
    symbols = re.findall(r'\{.*?}', text)
    if len(symbols) > 0:
        for symbol in symbols:
            symbol_img = f'<img class="mana-image-sm" src="{get_symbol_uri(symbol)}" alt="">'
            text = str(text).replace(symbol, symbol_img)
    return text


# @cache_page(60 * 15)
def home(request):
    try:
        card_sets = get_sets()
        cards = [
            dict(
                code=data['code'],
                symbol_url=data['icon_svg_uri'],
                name=data['name'],
                release_date=data['released_at']
            ) for data in card_sets
        ]
        print(cards)
        return render(request, 'app/card_sets.html', {'sets': cards})
    except Exception as e:
        return JsonResponse({'Error': str(e)})


# @cache_page(60 * 15)
def card_list(request, set_id: str):
    try:
        card_set = Set.find(set_id)
        rs = Card.where(set=set_id).all()
        # print(rs)
        cards = [
            {
                'name': r.name,
                'og_mana_cost': r.mana_cost,
                'mana_cost': r.mana_cost,
                'color_identity': r.color_identity,
                'colors': r.colors,
                'id': r.id,
                'type': r.type,
                'subtypes': r.subtypes,
                'text': convert_symbols(r.text) if r.text else '',
                'image_url': r.image_url,
                'power': r.power,
                'flavor': r.flavor,
                'toughness': r.toughness,
                # 'card_no': r.card_no
            }
            for r in rs
        ]

        context = {
            'cards': cards,
            'title': card_set.name,
            'card_set': card_set
        }
        return render(request, 'app/cards.html', context)
    except TypeError as e:
        return JsonResponse({'TypeError': str(e)})
    except Exception as e:
        return JsonResponse({'Error': str(e)})


# @cache_page(60 * 15)
def card_image(request, card_id: str):
    try:
        response = requests.get(SCRYFALL_API + '/cards/' + card_id)
        if response.status_code == 200:
            # print(response.json())
            obj = response.json()
        else:
            obj = {
                'type': '',
                'set': '',
                'text': '',
                'power': None,
                'toughness': None,
                'flavor': '',
                'name': '',
                'mana_cost': '',
                'image_uris': {'normal': ''},
                'oracle_text': ''
            }
        # obj = Card.find(card_id)
        print(obj)
        r_set = requests.get('https://api.scryfall.com/sets/'+obj['set'])
        if r_set.status_code == 200:
            card_set = r_set.json()
        else:
            card_set = None
        o_text = convert_symbols(obj['oracle_text'])
        o_card = {
            'text': o_text,
            'power': obj['power'] if 'power' in obj else None,
            'toughness': obj['toughness'] if 'toughness' in obj else None,
            'name': obj['name'],
            'type': obj['type_line'] if 'type_line' in obj else None,
            'flavor': obj['flavor_text'] if 'flavor_text' in obj else None,
            'mana_cost': obj['mana_cost'],
            'image_url': obj['image_uris']['normal'],
            'set': obj['set'],
            'oracle_text': obj['oracle_text']


        }
        context = {'title': 'Card Image', 'obj': o_card, 'card_set': card_set}
        return render(request, 'app/card_image.html', context)
    except Exception as e:
        return JsonResponse({'Error': str(e)})


def card_search(request):
    try:
        context = {'title': 'Card Search', 'srch_term': ''}
        if request.method == 'POST':
            form = SearchForm(request.POST or None)
            if form.is_valid():
                search = form.cleaned_data['search']
                context['srch_term'] = search
                print(search)
                response = requests.get('https://api.scryfall.com/cards/search?q=%s' % search)
                if response.status_code == 200:
                    srch_results = response.json()['data']
                    if len(srch_results) > 0:
                        cards = [
                            {
                                'id': result['id'],
                                'name': result['name'],
                                'image_url': result['image_uris']['normal'] if 'image_uris' in result else '',
                                'oracle_id': result['oracle_id'],
                                'text': convert_symbols(result['oracle_text']) if 'oracle_text' in result else convert_symbols(result['card_faces'][0]['oracle_text']),
                                'type': result['type_line'],
                                'mana_cost': result['mana_cost'] if 'mana_cost' in result else result['card_faces'][0]['mana_cost'],
                                'flavor': result['flavor_text']
                            }
                            for result in srch_results
                        ]
                        context['cards'] = cards
                else:
                    return JsonResponse({'Response': response.status_code})
        return render(request, 'app/cards.html', context)
    # return HttpResponse('Hello')
    except TypeError as e:
        return JsonResponse({'TypeError': str(e)})
    except Exception as e:
        return JsonResponse({'Error': str(e)})

app/templates/app/card_image.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb card_set.code 'app:card_list' card_set.code %}
    {% breadcrumb obj.name 'app:card_image' obj.id %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="small" id="breadcrumbs">{% render_breadcrumbs %}</div>
        <div class="row">
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-header">
                        <h1>{{ obj.name }}</h1>
                    </div>
                    <div class="card-body">
                        <img class="card-img" src="{{ obj.image_url }}" alt="{{ obj.name }}">
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-8">
                                {{ obj.type }}
                            </div>
                            <div class="col-sm-4 me-auto text-end">
                                {% for m in obj.mana_cost %}
                                    <img class="img-fluid mana-image" src="https://svgs.scryfall.io/card-symbols/{{m|get_symbol}}.svg" alt="{{ m|get_symbol }}">
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-8">
                                {% if obj.power %}
                                    {{ obj.power }}/{{ obj.toughness }}
                                {% endif %}
                            </div>
                            <div class="col-sm-4">&nbsp;</div>
                        </div>
                    </div>
                    <div class="card-body">
                        {{ obj.text| safe }}
                    </div>
                    {% if obj.flavor %}
                        <div class="card-body">
                            <i>{{ obj.flavor }}</i>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}

app/templates/app/card_sets.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% block content %}
    <div class="container">
        <div class="small" id="breadcrumbs">{% render_breadcrumbs %}</div>
        <div class="card">
            <div class="card-header">
                <h1>MtG Sets</h1>
            </div>
            <div class="card-body scroll">
                <table class="display" id="myTable">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Card Set</th>
                            <th>Icon</th>
                            <th>Released</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for s in sets %}
                            {% if s.code|length == 3 %}
                                <tr>
                                    <td>{{ s.code }}</td>
                                    <td><a href="{% url 'app:card_list' s.code %}">{{ s.name }}</a></td>
                                    <td><img class="img-fluid mana-image" src="{{ s.symbol_url }}" alt="{{ s.code }}"></td>
                                    <td>{{ s.release_date }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ sets|length }} Items</small>
            </div>
        </div>
    </div>
    <script>
        let table = new DataTable(
            '#myTable',
            {
                order: [[3, 'asc']],
                lengthMenu: [[25, 50, 100, -1], [25, 50, 100, 'All']]
            }
        )
    </script>
{% endblock %}

app/templates/app/cards.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% if srch_term %}
        {% breadcrumb 'Search' 'app:card_search' %}
    {% else %}
        {% breadcrumb card_set.code 'app:card_list' card_set.code %}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="small" id="breadcrumbs">{% render_breadcrumbs %}</div>
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-12 align-middle">
                        <h1>{% if srch_term %}{{ title }} - {{ srch_term }}{% else %}{{ card_set.name }}{% endif %}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body scroll">
                <table class="display" id="myTable">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Card Info</th>
                            <th>Mana cost</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in cards %}
{#                            {% if c.image_url %}#}
                            <tr>
                                <td>
                                    <a href="{% url 'app:card_image' c.id %}">
                                        <img class="img-thumbnail" src="{{ c.image_url }}" alt="{{ c.name }}">
                                    </a>
                                </td>
                                <td class="col-sm-8 align-text-top">
                                    <p><a href="{% url 'app:card_image' c.id %}">{{ c.name }}</a></p>
                                    <p>{{ c.type }}</p>
                                    <p class="small text-muted">{{ c.text|safe }}</p>
                                    {% if c.flavor %}
                                        <p class="small text-muted"><i>{{ c.flavor }}</i></p>
                                    {% endif %}
                                    {% if c.power %}
                                        <p>{{ c.power }}/{{ c.toughness }}</p>
                                    {% endif %}
                                </td>
                                <td class="align-text-top col-sm-2">
{#                                    {{ c.mana_cost }}#}
                                    {% for m in c.mana_cost %}
                                        <img class="img-fluid mana-image" src="https://svgs.scryfall.io/card-symbols/{{m | get_symbol}}.svg" alt="{{ m|get_symbol }}">
{#                                        <img class="img-fluid mana-image" src="{{ m| get_symbol_uri }}" alt="{{ m|get_symbol }}">#}
                                    {% endfor %}
                                </td>
                            </tr>
{#                            {% endif %}#}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ cards|length }} Items</small>
            </div>
        </div>
    </div>
    <script>
        let table = new DataTable(
            '#myTable',
            {
                order: [[1, 'asc']],
                lengthMenu: [[25, 50, 100, -1], [25, 50, 100, 'All']]
            }
        )
    </script>
{% endblock %}

templates/_search_filter.html
<label for="myInput"></label>
<input type="text" id="myInput" class="form-control form-control-sm" placeholder="Filter results...">
<span class="m-1" id="filterResults"></span>

templates/_toggle_mode.html
{% if request.COOKIES.toggle_mode and request.COOKIES.toggle_mode == 'dark' %}
    <i id="toggle-mode" class="fa fa-sun-o text-light"></i>
{% else %}
    <i id="toggle-mode" class="fa fa-moon-o text-dark"></i>
{% endif %}

templates/base.html
{% load django_bootstrap5 %}
{% load django_bootstrap_breadcrumbs %}
{% load static %}
<!DOCTYPE html>
{% if request.COOKIES.toggle_mode and request.COOKIES.toggle_mode == 'dark' %}
    <html lang="en" data-bs-theme="dark">
{% else %}
    <html lang="en">
{% endif %}

<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{#    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >#}

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- fontawesome -->
    <link rel="stylesheet" href="{% static 'fontawesome/font-awesome.min.css' %}">

    <!-- JQUERY -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'jquery-ui/jquery-ui.js' %}"></script>
    <link href="{% static 'jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
    <script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>

    <script src="{% static 'datatables/dataTables.js' %}"></script>
    <link href="{% static 'datatables/dataTables.css' %}" rel="stylesheet">

    <link href="{% static 'css/custom.css'  %}" rel="stylesheet">

    {% if title %}
		<title>Planet 8 Design - MTG: {{ title }}</title>
	{% else %}
		<title>Planet 8 Design - MTG</title>
	{% endif %}

</head>

<body>
    <header class="site-header">
        <nav id="my-navbar" class="navbar navbar-expand-md navbar-dark {% if request.COOKIES.toggle_mode and request.COOKIES.toggle_mode == 'dark' %}bg-dark{% else %}bg-light{% endif %} fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'app:home' %}">
                    <img class="img-fluid" src="{% static 'images/mtg-logo-2017.png' %}" alt="logo">
{#                    <span class="navHeader">Planet 8 Design</span>#}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" id="toggle-link" href="#togglemode">{% include '_toggle_mode.html' %}</a>
                        </li>
                        <li class="nav-item">
                            <form method="post" action="{% url 'app:card_search' %}">
                                {% csrf_token %}
                                <div class="input-group">
                                    <label for="search"></label>
                                    <input type="text" name="search" id="search" class="form-control form-control-lg rounded-start" placeholder="Search...">
                                    <button id="search-btn" class="btn btn-lg {% if request.COOKIES.toggle_mode and request.COOKIES.toggle_mode == 'dark' %}btn-dark btn-outline-secondary{% else %}btn-light btn-outline-dark{% endif %}"><i class="fa fa-search"></i></button>
                                </div>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>	
	<main role="main" class="container">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        {% block breadcrumbs %}
            {% clear_breadcrumbs %}
            {% breadcrumb "Sets List" "/" %}
        {% endblock breadcrumbs %}

      <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissable">{{ message }}</div>
                {% endfor %}
            {% endif %}

            {% block content %}
                {% render_breadcrumbs %}
            {% endblock %}
        </div>
      </div>

    </main>
    <div class="container">
        <hr>
        <footer class="site-footer">
            <p>
                <small class="text-muted">MTG, JOJODAVE &copy; DC 2021-{{ copyright_year }}</small>
            </p>
        </footer>
    </div>
    <script>
        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                let value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
                    $("#searchCount").html()
                });
            });
        });
        $('#toggle-link').on('click', function () {
            let html_tag = $('html');
            let mode = html_tag.attr('data-bs-theme');
            let this_mode = mode ? null : 'dark';
            html_tag.attr('data-bs-theme', this_mode);
            $.ajax({
                url: '/toggle_mode/'+this_mode+'/',
                type: 'GET',
                success: function(res) {
                    $('#toggle-link').html(res);
                }
            });
            
            console.log(this_mode);
            
            if (this_mode === 'dark') {
                $('#my-navbar')
                    .addClass('bg-dark')
                    .removeClass('bg-light');
                $('#search-btn')
                    .addClass('btn-dark')
                    .addClass('btn-outline-secondary')
                    .removeClass('btn-outline-dark')
                    .removeClass('btn-light');
                $('#toggle-mode')
                    .addClass('text-light')
                    .removeClass('text-dark')
                    .removeClass('fa-moon-o')
                    .addClass('fa-sun-o');
            }
            else {
                $('#my-navbar')
                    .addClass('bg-light')
                    .removeClass('bg-dark');
                $('#search-btn')
                    .addClass('btn-light')
                    .addClass('btn-outline-dark')
                    .removeClass('btn-outline-secondary')
                    .removeClass('btn-dark');
                $('#toggle-mode')
                    .addClass('text-dark')
                    .removeClass('text-light')
                    .removeClass('fa-sun-o')
                    .addClass('fa-moon-o');
            }
        });
    </script>
</body>
</html>

templates/card_image.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb card_set.code 'app:card_list' card_set.code %}
    {% breadcrumb obj.name 'app:card_image' obj.id %}
{% endblock %}
{% block content %}
    <div class="container">
        <div id="breadcrumbs">{% render_breadcrumbs %}</div>
        <div class="row">
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-header">
                        <h1>{{ obj.name }}</h1>
                    </div>
                    <div class="card-body">
                        <img class="card-img" src="{{ obj.image_url }}" alt="{{ obj.name }}">
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-8">
                                {{ obj.type }}
                            </div>
                            <div class="col-sm-4 me-auto text-end">
                                {{ obj.mana_cost }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-8">
                                {% if obj.power %}
                                    {{ obj.power }}/{{ obj.toughness }}
                                {% endif %}
                            </div>
                            <div class="col-sm-4">&nbsp;</div>
                        </div>
                    </div>
                    <div class="card-body">
                        {{ obj.text }}
                    </div>
                    {% if obj.flavor %}
                        <div class="card-body">
                            <i>{{ obj.flavor }}</i>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}

templates/card_sets.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% block content %}
    <div class="container">
        <div id="breadcrumbs">{% render_breadcrumbs %}</div>
        <div class="card">
            <div class="card-header">
                <h1>MtG Sets</h1>
            </div>
            <div class="card-body scroll">
                <table class="display" id="myTable">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Card Set</th>
                            <th>Icon</th>
                            <th>Released</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for s in sets %}
                            <tr>
                                <td>{{ s.code }}</td>
                                <td><a href="{% url 'app:card_list' s.code %}">{{ s.name }}</a></td>
                                <td><img class="img-fluid mana-image" src="{{ s.symbol_url }}" alt="{{ s.code }}"></td>
                                <td>{{ s.release_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ sets|length }}</small>
            </div>
        </div>
    </div>
    <script>
        let table = new DataTable(
            '#myTable', 
            {
                order: [[3, 'asc']], 
                lengthMenu: [[25, 50, 100, -1], [25, 50, 100, 'All']]
            }
        )
    </script>
{% endblock %}

templates/cards.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb card_set.code 'app:card_list' card_set.code %}
{% endblock %}
{% block content %}
    <div class="container">
        <div id="breadcrumbs">{% render_breadcrumbs %}</div>
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-8 align-middle">
                        <h1>{{ card_set.name }}</h1>
                    </div>
                    <div class="col-sm-4 me-auto text-end">
{#                        {% include '_search_filter.html' %}#}
                    </div>
                </div>
            </div>
            <div class="card-body scroll">
                <table class="display" id="myTable">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Card Info</th>
                            <th>Mana cost</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in cards %}
                            {% if c.image_url %}
                            <tr>
                                <td>
                                    <a href="{% url 'app:card_image' c.id %}">
                                        <img class="img-thumbnail" src="{{ c.image_url }}" alt="{{ c.name }}">
                                    </a>
                                </td>
                                <td class="col-sm-8 align-text-top">
                                    <p><a href="{% url 'app:card_image' c.id %}">{{ c.name }}</a></p>
                                    <p>{{ c.type }}</p>
                                    <p class="small text-muted">{{ c.text }}</p>
                                    {% if c.power %}
                                        <p>{{ c.power }}/{{ c.toughness }}</p>
                                    {% endif %}
                                </td>
                                <td class="align-text-top">
                                    {% for m in c.mana_cost %}
                                        <img class="img-fluid mana-image" src="https://svgs.scryfall.io/card-symbols/{{m}}.svg" alt="{{ m }}">
                                    {% endfor %}
                                </td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ cards|length }}</small>
            </div>
        </div>
    </div>
    <script>
        let table = new DataTable(
            '#myTable', 
            {
                order: [[2, 'asc']], 
                lengthMenu: [[25, 50, 100, -1], [25, 50, 100, 'All']]
            }
        )
    </script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% block content %}
    <div class="container">
        <div id="breadcrumbs">{% render_breadcrumbs %}</div>
        <div class="card">
            <div class="card-header">
                <h1>MtG Sets</h1>
            </div>
            <div class="card-body scroll">
                <table class="display" id="myTable">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Card Set</th>
                            <th>Released</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for s in sets %}
                            <tr>
                                <td>{{ s.code }}</td>
                                <td><a href="{% url 'app:card_list' s.code %}">{{ s.name }}</a></td>
                                <td>{{ s.release_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ sets|length }}</small>
            </div>
        </div>
    </div>
    <script>
        let table = new DataTable('#myTable')
    </script>
{% endblock %}